name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    
    - name: Install dependencies
      run: |
        forge install openzeppelin/openzeppelin-contracts --no-commit
        forge install openzeppelin/openzeppelin-contracts-upgradeable --no-commit
    
    - name: Check formatting
      run: forge fmt --check
    
    - name: Build contracts
      run: forge build
    
    - name: Run tests
      run: forge test -vvv
    
    - name: Run tests with gas reporting
      run: forge test --gas-report
    
    - name: Run linting
      run: |
        npm install -g solhint
        solhint "src/**/*.sol"
    
    - name: Run security analysis
      run: |
        forge install crytic/slither-analyzer --no-commit
        slither src/Vesting721Of721Plus.sol --exclude-dependencies

  deploy-base-sepolia:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    
    - name: Install dependencies
      run: |
        forge install openzeppelin/openzeppelin-contracts --no-commit
        forge install openzeppelin/openzeppelin-contracts-upgradeable --no-commit
    
    - name: Deploy to Base Sepolia
      run: |
        forge script script/Deploy.s.sol:DeployScript \
          --rpc-url ${{ secrets.BASE_SEPOLIA_RPC_URL }} \
          --private-key ${{ secrets.PRIVATE_KEY }} \
          --broadcast \
          --verify \
          --etherscan-api-key ${{ secrets.BASESCAN_API_KEY }}
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  deploy-base-mainnet:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    
    - name: Install dependencies
      run: |
        forge install openzeppelin/openzeppelin-contracts --no-commit
        forge install openzeppelin/openzeppelin-contracts-upgradeable --no-commit
    
    - name: Deploy to Base Mainnet
      run: |
        forge script script/Deploy.s.sol:DeployScript \
          --rpc-url ${{ secrets.BASE_MAINNET_RPC_URL }} \
          --private-key ${{ secrets.PRIVATE_KEY }} \
          --broadcast \
          --verify \
          --etherscan-api-key ${{ secrets.BASESCAN_API_KEY }}
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
